Repository foxbit-group/foxbit-api-samples, pull requests merged in 2024-02, with the labels that each got.

#3 feat: adding codeowner file
  .github/CODEOWNERS
Labels: feature

#2 Implementing PHP examples and get active orders
  README.md
  rest-v3/dotnet/Program.cs
  rest-v3/go/examples.go
  rest-v3/java/src/main/java/br/com/foxbit/samples/FoxbitApiSamples.java
  rest-v3/javascript/examples.js
  rest-v3/php/.gitignore
  rest-v3/php/README.md
  rest-v3/php/composer.json
  rest-v3/php/composer.lock
  rest-v3/php/examples.php
  rest-v3/python/README.md
  rest-v3/python/examples.py
  rest-v3/ruby/examples.rb
  rest-v3/typescript/examples.ts
Labels: enhancement

#4 enhance: adjusting WebSocket v2 examples
  websocket-v2/javascript/index.js
  websocket-v2/javascript/package-lock.json
  websocket-v2/javascript/package.json
Labels: enhancement

#5 Create README.md for "rest-v3" folder
  rest-v3/README.md
  rest-v3/dotnet/README.md
  rest-v3/go/README.md
  rest-v3/java/README.md
  rest-v3/javascript/README.md
  rest-v3/php/README.md
  rest-v3/python/README.md
  rest-v3/ruby/README.md
  rest-v3/typescript/README.md
Labels: documentation, feature
